/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_handsome_ndkdemo_MainActivity */

#ifndef _Included_com_handsome_ndkdemo_MainActivity
#define _Included_com_handsome_ndkdemo_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_handsome_ndkdemo_MainActivity
 * Method:    accessField
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_handsome_ndkdemo_MainActivity_accessField
  (JNIEnv *, jobject);

/*
 * Class:     com_handsome_ndkdemo_MainActivity
 * Method:    accessStaticField
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_handsome_ndkdemo_MainActivity_accessStaticField
  (JNIEnv *, jobject);

/*
 * Class:     com_handsome_ndkdemo_MainActivity
 * Method:    accessMethod
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_handsome_ndkdemo_MainActivity_accessMethod
  (JNIEnv *, jobject);

/*
 * Class:     com_handsome_ndkdemo_MainActivity
 * Method:    accessStaticMethod
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_handsome_ndkdemo_MainActivity_accessStaticMethod
  (JNIEnv *, jobject);

/*
 * Class:     com_handsome_ndkdemo_MainActivity
 * Method:    accessConstructor
 * Signature: ()Ljava/util/Date;
 */
JNIEXPORT jobject JNICALL Java_com_handsome_ndkdemo_MainActivity_accessConstructor
  (JNIEnv *, jobject);

/*
 * Class:     com_handsome_ndkdemo_MainActivity
 * Method:    accessNonvirtualMethod
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_handsome_ndkdemo_MainActivity_accessNonvirtualMethod
  (JNIEnv *, jobject);

/*
 * Class:     com_handsome_ndkdemo_MainActivity
 * Method:    chineseChars
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_handsome_ndkdemo_MainActivity_chineseChars
  (JNIEnv *, jobject);

/*
 * Class:     com_handsome_ndkdemo_MainActivity
 * Method:    giveArray
 * Signature: ([I)V
 */
JNIEXPORT void JNICALL Java_com_handsome_ndkdemo_MainActivity_giveArray
  (JNIEnv *, jobject, jintArray);

/*
 * Class:     com_handsome_ndkdemo_MainActivity
 * Method:    getArray
 * Signature: (I)[I
 */
JNIEXPORT jintArray JNICALL Java_com_handsome_ndkdemo_MainActivity_getArray
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_handsome_ndkdemo_MainActivity
 * Method:    localRef
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_handsome_ndkdemo_MainActivity_localRef
  (JNIEnv *, jobject);

/*
 * Class:     com_handsome_ndkdemo_MainActivity
 * Method:    createGlobalRef
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_handsome_ndkdemo_MainActivity_createGlobalRef
  (JNIEnv *, jobject);

/*
 * Class:     com_handsome_ndkdemo_MainActivity
 * Method:    getGlobalRef
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_handsome_ndkdemo_MainActivity_getGlobalRef
  (JNIEnv *, jobject);

/*
 * Class:     com_handsome_ndkdemo_MainActivity
 * Method:    deleteGlobalRef
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_handsome_ndkdemo_MainActivity_deleteGlobalRef
  (JNIEnv *, jobject);

/*
 * Class:     com_handsome_ndkdemo_MainActivity
 * Method:    exeception
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_handsome_ndkdemo_MainActivity_exeception
  (JNIEnv *, jobject);

/*
 * Class:     com_handsome_ndkdemo_MainActivity
 * Method:    cached
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_handsome_ndkdemo_MainActivity_cached
  (JNIEnv *, jobject);

/*
 * Class:     com_handsome_ndkdemo_MainActivity
 * Method:    initIds
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_handsome_ndkdemo_MainActivity_initIds
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
